---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager-role-binding
  namespace: default
subjects:
- kind: Group
  name: system:serviceaccounts:default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role