apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: conductor
  name: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: conductor
    spec:
      containers:
        - env:
            - name: NATS_URI
              value: nats://nats:4222
          image: conductor
          name: conductor
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
