version: "3"

services:
  musician:
    depends_on:
      - nats
    image: musician
    build:
      context: ./musician
      dockerfile: Dockerfile
    environment:
      NATS_URI: nats://nats:4222

  server:
    depends_on:
      - nats
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NATS_URI: nats://nats:4222
    ports:
      - "1323:1323"

  conductor:
    image: conductor
    depends_on:
      - nats
    build:
      context: ./conductor/
      dockerfile: Dockerfile
    environment:
      NATS_URI: nats://nats:4222

  nats:
    image: "nats:latest"
    entrypoint: "/nats-server"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
