apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-music
  labels:
    app: music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music

  template:
    metadata:
      name: music
      labels:
        app: music
    spec:
      containers:
      - name: conductor
        image: conductor
        imagePullPolicy: Never
      - name: nats
        image: nats:latest
