apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nats
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nats
    spec:
      containers:
        - command:
            - /nats-server
          image: nats:latest
          name: nats
          ports:
            - containerPort: 8222
            - containerPort: 4222
          resources: {}
      hostname: nats-server
      restartPolicy: Always
status: {}
